# Generated by Django 4.2.1 on 2023-05-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0003_menuitemimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemimage',
            old_name='product',
            new_name='menu_item',
        ),
    ]
